In [2]:
import numpy as np

In [3]:
mu1 = -3
mu2 = 2
sig1 = 4
sig2 = 4
p1 = 0.5
p2 = 0.5

In [31]:
x1 = 0.2
x2 = -0.9
x3 = -1
x4 = 1.2
x5 = 1.8

In [32]:
p11 = p1 * gauss(x1, mu1, sig1) / ((p1 * gauss(x1, mu1, sig1)) + (p2 * gauss(x1, mu2, sig2)))
p12 = p1 * gauss(x2, mu1, sig1) / ((p1 * gauss(x2, mu1, sig1)) + (p2 * gauss(x2, mu2, sig2)))
p13 = p1 * gauss(x3, mu1, sig1) / ((p1 * gauss(x3, mu1, sig1)) + (p2 * gauss(x3, mu2, sig2)))
p14 = p1 * gauss(x4, mu1, sig1) / ((p1 * gauss(x4, mu1, sig1)) + (p2 * gauss(x4, mu2, sig2)))
p15 = p1 * gauss(x5, mu1, sig1) / ((p1 * gauss(x5, mu1, sig1)) + (p2 * gauss(x5, mu2, sig2)))

0.29421497216298875

In [41]:
n1_hat = p11 + p12 + p13 + p14 + p15
n1_hat

1.728123091776373

In [42]:
p1_hat = n1_hat/5
p1_hat

0.3456246183552746

In [43]:
mu1_hat = 1/n1_hat * (p11*x1 + p12*x2 + p13*x3 + p14*x4 + p15*x5)
mu1_hat

-0.5373289474340417

In [44]:
sig1_hat = 1/n1_hat * (p11*(x1-mu1_hat)**2 + p12*(x2-mu1_hat)**2 + p13*(x3-mu1_hat)**2 + p14*(x4-mu1_hat)**2 + p15*(x5-mu1_hat)**2)
sig1_hat

0.5757859076870628

In [45]:
p21 = p1 * gauss(x1, mu2, sig2) / ((p1 * gauss(x1, mu1, sig1)) + (p2 * gauss(x1, mu2, sig2)))
p22 = p1 * gauss(x2, mu2, sig2) / ((p1 * gauss(x2, mu1, sig1)) + (p2 * gauss(x2, mu2, sig2)))
p23 = p1 * gauss(x3, mu2, sig2) / ((p1 * gauss(x3, mu1, sig1)) + (p2 * gauss(x3, mu2, sig2)))
p24 = p1 * gauss(x4, mu2, sig2) / ((p1 * gauss(x4, mu1, sig1)) + (p2 * gauss(x4, mu2, sig2)))
p25 = p1 * gauss(x5, mu2, sig2) / ((p1 * gauss(x5, mu1, sig1)) + (p2 * gauss(x5, mu2, sig2)))

In [46]:
n2_hat = p21 + p22 + p23 + p24 + p25
n2_hat

3.271876908223627

In [47]:
p2_hat = n2_hat/5
p2_hat

0.6543753816447254

In [48]:
mu2_hat = 1/n2_hat * (p21*x1 + p22*x2 + p23*x3 + p24*x4 + p25*x5)
mu2_hat

0.681129096372577

In [49]:
sig2_hat = 1/n2_hat * (p21*(x1-mu2_hat)**2 + p22*(x2-mu2_hat)**2 + p23*(x3-mu2_hat)**2 + p24*(x4-mu2_hat)**2 + p25*(x5-mu2_hat)**2)
sig2_hat

1.0752479631618013

In [4]:
def gauss(x, mu, sigma_sq):
    return 1 / np.sqrt(2*np.pi*sigma_sq) * np.exp(-(x - mu)**2 / (2 * sigma_sq))

In [5]:
ps = [0.5, 0.5]
mus = [6, 7]
sigs = [1, 4]

X = [-1, 0, 4, 5, 6]
n = len(X)
K = 2

In [4]:
res = []

for x in X:
    res.append(ps[0]*gauss(x, mus[0], sigs[0]) + ps[1]*gauss(x, mus[1], sigs[1]))

In [5]:
np.log(res[0]*res[1]*res[2]*res[3]*res[4])

-24.512532330086678

In [6]:
res

[3.3457561008581545e-05,
 0.00021817371170286496,
 0.05937488217306697,
 0.18147804338935752,
 0.28748747189179125]

In [8]:
for i in range(len(X)):
    print(ps[0] * gauss(X[i], mus[0], sigs[0])/res[i]>ps[1] * gauss(X[i], mus[1], sigs[1])/res[i])

False
False
False
True
True


In [176]:
def gauss(x, mu, sigma_sq):
    return 1 / np.sqrt(2*np.pi*sigma_sq) * np.exp(-(x - mu)**2 / (2 * sigma_sq))

In [395]:
ps = np.array([0.5, 0.5])
mus = np.array([6., 7.])
sigs = np.array([1., 4.])
X = np.array([-1, 0, 4, 5, 6])
n = len(X)
K = 2

r = np.zeros((n, K))

In [396]:
trials = 100

for trial in range(trials):
    #print('step:,',trial)

    
    # E-step
    for j in range(K):
        for i in range(n):
            r[i][j] = ps[j]*gauss(X[i], mus[j], sigs[j])
    for i in range(n):
        r[i] /= (np.sum(r,axis=1)[i])
    
    n_k = np.sum(r, axis=0)
    # M step
    for j in range(K):
        mus[j] = np.dot(r[:, j], X)/n_k[j]
        sigs[j] = np.dot(r[:, j], (X - mus[j])**2) / n_k[j]
        ps[j] = n_k[j]/n

print('probabilities:', ps)
print('means:',mus)
print('sigmas:', sigs)

probabilities: [0.6 0.4]
means: [ 4.99999998 -0.5       ]
sigmas: [0.66666676 0.25      ]


In [139]:
X = np.array([[0.85794562, 0.84725174],
 [0.6235637,  0.38438171],
 [0.29753461, 0.05671298],
 [0.27265629, 0.47766512],
 [0.81216873, 0.47997717],
 [0.3927848,  0.83607876],
 [0.33739616, 0.64817187],
 [0.36824154, 0.95715516],
 [0.14035078, 0.87008726],
 [0.47360805, 0.80091075],
 [0.52047748, 0.67887953],
 [0.72063265, 0.58201979],
 [0.53737323, 0.75861562],
 [0.10590761, 0.47360042],
 [0.18633234, 0.73691818]])

n = len(X)
K = 6

mu = np.array([[0.6235637,  0.38438171],
 [0.3927848,  0.83607876],
 [0.81216873, 0.47997717],
 [0.14035078, 0.87008726],
 [0.36824154, 0.95715516],
 [0.10590761, 0.47360042]])

sig = np.array([0.10038354, 0.07227467, 0.13240693, 0.12411825, 0.10497521, 0.12220856])

p =  np.array([0.1680912,  0.15835331, 0.21384187, 0.14223565, 0.14295074, 0.17452722])


In [140]:
def gauss(x, mu, sigma_sq):
    return 1 / (2*np.pi*sigma_sq) * np.exp(-np.linalg.norm(x - mu)**2 / (2 * sigma_sq))

In [141]:
r = np.zeros((n, K))

for j in range(K):
    for i in range(n):
        r[i][j] = p[j]*gauss(X[i], mu[j], sig[j])
        
for i in range(n):
    r[i] /= (np.sum(r,axis=1)[i])
    
ll = 0

for i in range(n):
    tmp = 0
    for j in range(K):
        tmp += p[j] * gauss(X[i], mu[j], sig[j])
    ll += np.log(tmp)
    
#ll = np.sum(np.log())
ll

-5.592899125423124

In [229]:
post = r

n, d = X.shape
_, K = post.shape

min_variance = 0.25

mus = np.zeros((K, d))
sigs = np.zeros((K, ))
ps = np.zeros((K, ))

n_hat = np.sum(post, axis=0)

for j in range(K):
    ps[j] = n_hat[j]/n
    mus[j] = np.matmul(post[:, j], X)/n_hat[j]    
    sigs[j] = np.sum(np.dot(post[:, j], np.power(X - mus[j], 2))) / (n_hat[j] * d)


In [230]:
np.sum(np.dot(post[:, j], np.power(X - mus[j], 2)))

0.2398618216860094

In [231]:
np.linalg.norm(X[0] - mus[0])**2

0.21651689096224713

In [232]:
mus

array([[0.52331295, 0.52392857],
       [0.41528539, 0.73650289],
       [0.58894129, 0.58909453],
       [0.34452203, 0.70650629],
       [0.41665741, 0.74466777],
       [0.32203946, 0.5396801 ]])

In [233]:
sigs

array([0.05360839, 0.03181134, 0.04893283, 0.03727128, 0.03542344,
       0.05171667])

In [234]:
p

array([0.1680912 , 0.15835331, 0.21384187, 0.14223565, 0.14295074,
       0.17452722])