In [1]:
import numpy as np

In [2]:
T = np.zeros((6, 2, 6))
R = np.zeros((6, 2, 6))

In [3]:
T[0, 0, 0] = T[0, 1, 0] = 1
T[4, 0, 3] = T[5, 0, 4] = T[4, 1, 4] = T[5, 1, 5] = 1
T[1, 0, 0] = T[2, 0, 1] = T[3, 0, 2] = 1
T[1, 1, 3] = T[2, 1, 4] = T[3, 1, 5] = 0.7
T[1, 1, 1] = T[2, 1, 2] = T[3, 1, 3] = 0.3

In [4]:
for i in range(6):
    for j in range(2):
        for k in range(6):
            if i == k and i != 0:
                R[i, j, k] = (i + 4)**(-1/2)
            else:
                R[i, j, k] = np.absolute((k - i)**(1/3))

In [5]:
T

array([[[1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ]],

       [[1. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0.3, 0. , 0.7, 0. , 0. ]],

       [[0. , 1. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0.3, 0. , 0.7, 0. ]],

       [[0. , 0. , 1. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.3, 0. , 0.7]],

       [[0. , 0. , 0. , 1. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 1. , 0. ]],

       [[0. , 0. , 0. , 0. , 1. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 1. ]]])

In [6]:
R

array([[[0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
         1.70997595],
        [0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
         1.70997595]],

       [[1.        , 0.4472136 , 1.        , 1.25992105, 1.44224957,
         1.58740105],
        [1.        , 0.4472136 , 1.        , 1.25992105, 1.44224957,
         1.58740105]],

       [[1.25992105, 1.        , 0.40824829, 1.        , 1.25992105,
         1.44224957],
        [1.25992105, 1.        , 0.40824829, 1.        , 1.25992105,
         1.44224957]],

       [[1.44224957, 1.25992105, 1.        , 0.37796447, 1.        ,
         1.25992105],
        [1.44224957, 1.25992105, 1.        , 0.37796447, 1.        ,
         1.25992105]],

       [[1.58740105, 1.44224957, 1.25992105, 1.        , 0.35355339,
         1.        ],
        [1.58740105, 1.44224957, 1.25992105, 1.        , 0.35355339,
         1.        ]],

       [[1.70997595, 1.58740105, 1.44224957, 1.25992105, 1.        ,
         0.

In [9]:
Q_0 = np.zeros((6,2))
Q_1 = np.zeros((6,2))
gamma = 0.6
for s in range(6):
    for s_prime in range(6):
        for a in range(2):
            Q_1[s, a] += T[s, a, s_prime]*(R[s, a, s_prime] + gamma*max(Q_0[s_prime, 0], Q_0[s_prime, 1]))
Q

array([[0.        , 0.        ],
       [1.        , 1.01610881],
       [1.        , 1.00441922],
       [1.        , 0.99533408],
       [1.        , 0.35355339],
       [1.        , 0.33333333]])

In [23]:
T = np.zeros((4, 2, 4))
R = np.zeros((4, 2, 4))

In [24]:
T[0, 0, 1] = T[1, 0, 2] = T[2, 0, 3] = 1.0
T[0, 1, 1] = T[0, 1, 2] = T[1, 1, 2] = T[1, 1, 3] = 0.5
T[2, 1, 3] = 1.0
T

array([[[0. , 1. , 0. , 0. ],
        [0. , 0.5, 0.5, 0. ]],

       [[0. , 0. , 1. , 0. ],
        [0. , 0. , 0.5, 0.5]],

       [[0. , 0. , 0. , 1. ],
        [0. , 0. , 0. , 1. ]],

       [[0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ]]])

In [25]:
R[2, 0, 3] = 10
R[0, 1, 1] = R[0, 1, 2] = R[1, 1, 2] = -1
R[1, 1, 3] = R[2, 1, 3] = 9
R

array([[[ 0.,  0.,  0.,  0.],
        [ 0., -1., -1.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  9.]],

       [[ 0.,  0.,  0., 10.],
        [ 0.,  0.,  0.,  9.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [50]:
Q_0 = np.zeros((4,2))
gamma = 1/3
for _ in range(2):
    Q_1 = np.zeros((4,2))
    for s in range(4):
        for s_prime in range(4):
            for a in range(2):
                Q_1[s, a] += T[s, a, s_prime]*(R[s, a, s_prime] + gamma*max(Q_0[s_prime, 0], Q_0[s_prime, 1]))
    Q_0 = Q_1
Q_1

array([[ 1.33333333,  1.33333333],
       [ 3.33333333,  5.66666667],
       [10.        ,  9.        ],
       [ 0.        ,  0.        ]])